### ISSUE TITLE
Enum_cast with not defined int will return has_value() == true

### ISSUE THREAD

**Issue by florianbecker** [Neargye/magic_enum#216] opened 2022-10-05 05:47 UTC
I have created a bad case test for enum_magic and I would like to discuss if this is a bug or not.

```cpp
enum class Color { RED = 2, BLUE = 4, GREEN = 8 };
std::optional colorUnkown = magic_enum::enum_cast<Color>(7);
EXPECT_FALSE( colorUnkown.has_value() ); // colorUnkown.has_value() == true
```
This example will return has_value() == true. But a color with this value is not defined. The following another example will return has_value() == false. So this is correct for me. But this feels like inconsistency.

```cpp
enum class Color { RED = 2, BLUE = 4, GREEN = 8 };
std::optional colorPurple = magic_enum::enum_cast<Color>("PURPLE");
EXPECT_FALSE( colorPurple.has_value() ); // colorPurple.has_value() == false
```

Using magic_enum v0.8.1

UPDATE:
Seems like something with bitwise_operators? I have not using the namespace for that. But I think it should never work in any case...
```cpp
enum class Color { RED = 2, BLUE = 4, GREEN = 8 };
std::optional colorMax = magic_enum::enum_cast<Color>( 14 );
EXPECT_FALSE( colorMax.has_value() ); // has_value() == true
```

```cpp
enum class Color { RED = 2, BLUE = 4, GREEN = 8 };
std::optional colorMaxPlusOne = magic_enum::enum_cast<Color>( 15 );
EXPECT_FALSE( colorMaxPlusOne.has_value() ); // has_value() == false
```

**Comment by Neargye** [comment] 2022-10-05 08:13
Yes, the problem is that the library thinks that these are flags.

Now (if you don't use flags) you can do this
```cpp
#define MAGIC_ENUM_NO_CHECK_FLAGS
#include <magic_enum.hpp>
```

**Comment by florianbecker** [comment] 2022-10-05 10:23
Ok, thank you for the workaround. But strict, this is not correct, even if you use flags. Because you cannot represent any enum to that value... but you can represent it as a valid flag value. So if you represent enum_cast<Color>(7) there is no enum for that.

Is this handled as a bug? Or won't fix?

**Comment by Neargye** [comment] 2022-11-07 17:00
Fix in master
Will be include in next release

**Closed as completed** 2022-11-07 17:00 UTC
Labels: enhancement, question

**Comment by florianbecker** [comment] 2022-11-07 20:24
Thank you. Working perfect.
